// Decompiled with JetBrains decompiler
// Type: SadCatStudios.Rendering.ProfilingKey
// Assembly: Replaced.Rendering, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: D285D39E-64D8-4503-AC6E-53BD55A674A4
// Assembly location: G:\SteamLibrary\steamapps\common\REPLACED Demo\BepInEx\interop\Replaced.Rendering.dll

#nullable disable
namespace SadCatStudios.Rendering;

public enum ProfilingKey
{
  ScsInitializeRedererData,
  ScsIntegrateDfgLut,
  ScsIntegrateDiffuseLd,
  ScsIntegrateSpecularLd,
  ScsLightingPrepare,
  ScsTiledLightListBuild,
  ScsLightListHeatmap,
  ScsClusteredLightListBuild,
  ScsLightingMainLightShadows,
  ScsShadowMapping,
  ScsShadowMappingCascade0,
  ScsShadowMappingCascade1,
  ScsShadowMappingCascade2,
  ScsShadowMappingCascade3,
  ScsShadowMappingPunctual,
  ScsShadowMappingPunctualLights,
  ScsPresentShadowMapCascades,
  ScsWaitFor_Tll_DP_GI,
  ScsVolumetric,
  ScsVolumetricDensityBufferGeneration,
  ScsVolumetricDensityBufferLighting,
  ScsVolumetricGenerateDensityBufferLit,
  ScsVolumetricCameraScatteredLightIntegration,
  ScsFirmamentStage,
  ScsDownsampleMaxDepth,
  ScsSkyAndCloudsPass,
  ScsUpscaleSkyAndClouds,
  ScsClouds,
  ScsDepthPrepass,
  ScsDepthPyramid,
  ScsGenerateHIZMip,
  ScsGenerateRadinceMapMip,
  ScsCopyDepth,
  ScsMaskDecalPass,
  ScsDecalPass,
  ScsCopySceneColor,
  ScsSetupGeometryRendering,
  ScsGeometryOpaqueAndAlphaTest,
  ScsGeometryTransparent,
  ScsGenerateSceneColorMipmaps,
  ScsGeometryTransparentRough,
  ScsGeometryFakeFog,
  ScsGeometryEditorOnlyStuff,
  ScsUnsupportedMaterial,
  ScsGlobalIllumination,
  ScsSsdoEstimate,
  ScsSsdoFilter,
  ScsSsrTrace,
  ScsSsrResolve,
  ScsSsrFilter,
  ScsGITemporal,
  ScsDownsampleSceneData,
  ScsRadianceMapGeneration,
  ScsDownsampleNormals,
  ScsDownsampleNormalPyramid,
  ScsDownsampleLinearRoughness,
  ScsDownsampleDepthPyramid,
  ScsGenerateMipmapsSceneColor,
  ScsAntiAliasing,
  ScsResolveMsaa,
  ScsTaa,
  ScsDepthOfField,
  ScsDepthOfFieldComputeCoc,
  ScsDepthOfFieldCocStabilization,
  ScsDepthOfFieldDofPrefiler,
  ScsDepthOfFieldGenerateDofInput,
  ScsDepthOfFieldDownsampleCoc,
  ScsDepthOfFieldRenderBokeh,
  ScsDepthOfFieldBokehTaa,
  ScsDepthOfFieldHorizontalBlur,
  ScsDepthOfFieldVerticalBlur,
  ScsDepthOfFieldComposeDofImage,
  ScsDepthOfFieldDebug,
  ScsPostProcessing,
  ScsColorGradingLut,
  ScsBloomPrefiler,
  ScsBloomDownsample,
  ScsBloonUpsample,
  ScsFinalBlit,
  ScsPreviewCamera,
  ScsPreviewCameraGeometry,
  ScsPreviewCameraFinalBlit,
  ScsDevdbgAfterAntiAliasing,
  ScsGaussinaBlurDevdbg,
  ScsDevdbgAfterPostProcessing,
  ScsPixelization,
  ScsUIClearTextures,
  ScsUIGeometry,
  ScsUIResolveColor,
  ScsUIFullscreenVfx,
  ScsUIFinalBlit,
  ScsPresentToCameraRT,
}
