[package]
name = "nier_ultrawide_patcher"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0"
hex-literal = "0.3.4"
dialoguer = "0.9.0"
spinners = "2.0.0"
ureq = "2.3.1"