// Decompiled with JetBrains decompiler
// Type: UnityEngine.Rendering.BuiltinShaderDefine
// Assembly: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: E159F43B-803F-461A-9433-870981D20FB6
// Assembly location: G:\SteamLibrary\steamapps\common\REPLACED Demo\BepInEx\interop\UnityEngine.CoreModule.dll

#nullable disable
namespace UnityEngine.Rendering;

public enum BuiltinShaderDefine
{
  UNITY_NO_DXT5nm,
  UNITY_NO_RGBM,
  UNITY_USE_NATIVE_HDR,
  UNITY_ENABLE_REFLECTION_BUFFERS,
  UNITY_FRAMEBUFFER_FETCH_AVAILABLE,
  UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS,
  UNITY_METAL_SHADOWS_USE_POINT_FILTERING,
  UNITY_NO_CUBEMAP_ARRAY,
  UNITY_NO_SCREENSPACE_SHADOWS,
  UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS,
  UNITY_PBS_USE_BRDF1,
  UNITY_PBS_USE_BRDF2,
  UNITY_PBS_USE_BRDF3,
  UNITY_NO_FULL_STANDARD_SHADER,
  UNITY_SPECCUBE_BOX_PROJECTION,
  UNITY_SPECCUBE_BLENDING,
  UNITY_ENABLE_DETAIL_NORMALMAP,
  SHADER_API_MOBILE,
  SHADER_API_DESKTOP,
  UNITY_HARDWARE_TIER1,
  UNITY_HARDWARE_TIER2,
  UNITY_HARDWARE_TIER3,
  UNITY_COLORSPACE_GAMMA,
  UNITY_LIGHT_PROBE_PROXY_VOLUME,
  UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS,
  UNITY_LIGHTMAP_DLDR_ENCODING,
  UNITY_LIGHTMAP_RGBM_ENCODING,
  UNITY_LIGHTMAP_FULL_HDR,
  UNITY_VIRTUAL_TEXTURING,
  UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION,
  UNITY_ASTC_NORMALMAP_ENCODING,
  SHADER_API_GLES30,
  SHADER_API_GLES31,
  SHADER_API_GLES32,
  UNITY_UNIFIED_SHADER_PRECISION_MODEL,
  UNITY_PLATFORM_SUPPORTS_WAVE_32,
  UNITY_PLATFORM_SUPPORTS_WAVE_64,
  UNITY_NEEDS_RENDERPASS_FBFETCH_FALLBACK,
  UNITY_PLATFORM_SUPPORTS_DEPTH_FETCH,
}
